server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#≈‰÷√mapper.xml
mybatis:
  mapper-locations: classpath:/mapper/*.xml

